-- =====================================================================
-- Slate — initial database schema
--
-- Read this top to bottom and it tells the story of the product:
-- an organization (your agency) has users (your team) and clients
-- (the brands you manage). Each client has connected social accounts.
-- You write posts for a client, send them to the client for approval
-- via a private link, and once approved they get published to one or
-- more of that client's accounts. Metrics are collected afterwards.
--
-- Do not edit this file after it has been applied to a real database.
-- Changes go in a new numbered migration file (002_..., 003_...) so
-- that every database can replay the same sequence of steps.
-- =====================================================================

-- gen_random_uuid() lives here. Supabase has this available already;
-- "if not exists" makes running this twice harmless.
create extension if not exists pgcrypto;


-- ---------------------------------------------------------------------
-- Helper: keep updated_at honest
--
-- Rather than remembering to set updated_at in every UPDATE we write,
-- we attach this to each table and the database maintains it for us.
-- ---------------------------------------------------------------------
create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- ---------------------------------------------------------------------
-- Enumerated types
--
-- An enum is a column that can only ever hold one of a fixed list of
-- values. If code tries to write "aproved" (typo), the database rejects
-- it outright instead of silently storing nonsense that breaks a filter
-- three weeks later.
-- ---------------------------------------------------------------------

create type user_role as enum ('owner', 'admin', 'member');

create type client_status as enum ('active', 'archived');

create type social_platform as enum ('instagram', 'facebook');

-- Health of a connected account's access token.
--   active  — usable
--   expired — token ran out, needs refresh (phase 7)
--   revoked — the user disconnected us at Meta's end
--   error   — Meta rejected it for some other reason; see last_error
create type account_status as enum ('active', 'expired', 'revoked', 'error');

-- The post workflow you chose, with a revision loop:
--
--   draft ──> pending_approval ──> changes_requested ──> (back to draft)
--                    │
--                    └────────> approved ──> scheduled ──> published
--                                                      └─> failed
--   archived is a dead end from anywhere.
create type post_status as enum (
  'draft',
  'pending_approval',
  'changes_requested',
  'approved',
  'scheduled',
  'published',
  'failed',
  'archived'
);

-- Status of one post going to one specific account. Separate from
-- post_status because Instagram can succeed while Facebook fails.
create type target_status as enum (
  'pending',
  'publishing',
  'published',
  'failed',
  'skipped'
);

create type media_type as enum ('image', 'video');

create type approval_decision as enum ('approved', 'changes_requested');


-- ---------------------------------------------------------------------
-- organizations — one row per agency
--
-- Today this holds exactly one row: yours. It exists now so that if you
-- ever open Slate up to other agencies, the structure is already right
-- and no data has to be migrated.
-- ---------------------------------------------------------------------
create table organizations (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  -- URL-safe short name, e.g. "mayfield". Lowercase letters, numbers
  -- and hyphens only — enforced so it's always safe to put in a URL.
  slug        text not null unique,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  constraint organizations_slug_format check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);


-- ---------------------------------------------------------------------
-- users — your team members
--
-- auth_user_id is left empty for now. When we wire up real logins it
-- will point at Supabase Auth's own user record, linking "the person who
-- can log in" to "the person's profile and role in Slate".
-- ---------------------------------------------------------------------
create table users (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations (id) on delete cascade,
  auth_user_id    uuid unique,
  email           text not null,
  full_name       text,
  role            user_role not null default 'member',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- Emails are compared case-insensitively: Taylor@… and taylor@… are the
-- same person and only one of them can exist.
create unique index users_email_key on users (lower(email));
create index users_organization_id_idx on users (organization_id);


-- ---------------------------------------------------------------------
-- clients — the brands you manage
--
-- contact_email is where approval links get sent.
-- ---------------------------------------------------------------------
create table clients (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations (id) on delete cascade,
  name            text not null,
  contact_name    text,
  contact_email   text,
  status          client_status not null default 'active',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index clients_organization_id_idx on clients (organization_id);
create index clients_org_status_idx on clients (organization_id, status);


-- ---------------------------------------------------------------------
-- social_accounts — connected Instagram / Facebook accounts
--
-- platform_account_id is Meta's own ID: the Instagram Business account
-- ID, or the Facebook Page ID. facebook_page_id is the parent Page for
-- an Instagram account, which the publishing API needs.
--
-- SECURITY: the access token is stored encrypted, never in plain text.
-- The column is named so that writing a raw token into it looks obviously
-- wrong in code review. Encryption is implemented in phase 3, alongside
-- the OAuth callback that first obtains a token.
-- ---------------------------------------------------------------------
create table social_accounts (
  id                     uuid primary key default gen_random_uuid(),
  organization_id        uuid not null references organizations (id) on delete cascade,
  client_id              uuid not null references clients (id) on delete cascade,
  platform               social_platform not null,
  platform_account_id    text not null,
  username               text,
  display_name           text,
  profile_picture_url    text,
  facebook_page_id       text,
  access_token_encrypted text not null,
  token_expires_at       timestamptz,
  -- Which permissions this token actually carries. Worth storing: if Meta
  -- changes what was granted, we can detect it instead of guessing from a
  -- failed publish.
  scopes                 text[] not null default '{}',
  status                 account_status not null default 'active',
  last_error             text,
  last_synced_at         timestamptz,
  connected_by_user_id   uuid references users (id) on delete set null,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),

  -- The same Instagram account can't be connected twice within one
  -- organization. Reconnecting updates the existing row instead.
  constraint social_accounts_unique_per_org
    unique (organization_id, platform, platform_account_id)
);

create index social_accounts_client_id_idx on social_accounts (client_id);
create index social_accounts_organization_id_idx on social_accounts (organization_id);
-- Used by phase 7 to find tokens that need refreshing before they lapse.
create index social_accounts_token_expiry_idx
  on social_accounts (token_expires_at)
  where status = 'active';


-- ---------------------------------------------------------------------
-- posts — the content itself
--
-- A post holds the caption and media once. Where it actually gets sent
-- is recorded in post_targets, so one post can go to several accounts.
--
-- scheduled_at is an absolute moment in time (timestamptz). The separate
-- `timezone` column records which zone you *composed* it in, so the
-- calendar can show "9:00 AM Sydney" months later and still be right
-- across daylight saving changes.
--
-- Rollup rule for status once publishing runs:
--   all targets published        -> published
--   all targets failed           -> failed
--   a mix of published/failed    -> published  (check targets for detail)
-- ---------------------------------------------------------------------
create table posts (
  id                 uuid primary key default gen_random_uuid(),
  organization_id    uuid not null references organizations (id) on delete cascade,
  client_id          uuid not null references clients (id) on delete cascade,
  created_by_user_id uuid references users (id) on delete set null,
  status             post_status not null default 'draft',
  caption            text not null default '',
  -- Instagram convention: hashtags posted as the first comment so the
  -- caption itself stays clean.
  first_comment      text,
  scheduled_at       timestamptz,
  timezone           text not null default 'UTC',
  internal_notes     text,
  published_at       timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),

  -- A post can't be in the scheduled queue without a time to fire at.
  -- Without this it's possible to create a post that silently never runs.
  constraint posts_scheduled_requires_time
    check (status <> 'scheduled' or scheduled_at is not null)
);

create index posts_organization_id_idx on posts (organization_id);
create index posts_client_status_idx on posts (client_id, status);
-- Drives the calendar view: "show me this client's month".
create index posts_calendar_idx on posts (organization_id, scheduled_at);
-- Drives the scheduling engine in phase 5: "what is due right now?".
-- A partial index only covers scheduled rows, so it stays small and fast
-- however many published posts pile up over the years.
create index posts_due_idx on posts (scheduled_at) where status = 'scheduled';


-- ---------------------------------------------------------------------
-- post_media — images and videos attached to a post
--
-- The files live in Supabase Storage; storage_path points at them. We
-- keep the dimensions and size because Instagram rejects media outside
-- certain limits, and it's far better to catch that when you upload than
-- at 9am when the post is meant to go out.
--
-- `position` is carousel order, starting at 0.
-- ---------------------------------------------------------------------
create table post_media (
  id               uuid primary key default gen_random_uuid(),
  post_id          uuid not null references posts (id) on delete cascade,
  position         integer not null default 0,
  media_type       media_type not null,
  storage_path     text not null,
  public_url       text,
  mime_type        text,
  file_size_bytes  bigint,
  width            integer,
  height           integer,
  duration_seconds numeric(10, 3),
  created_at       timestamptz not null default now(),

  constraint post_media_unique_position unique (post_id, position),
  constraint post_media_position_non_negative check (position >= 0)
);

create index post_media_post_id_idx on post_media (post_id, position);


-- ---------------------------------------------------------------------
-- post_targets — where a post is being sent, and how that went
--
-- One row per (post, account) pair. This is the table the publishing
-- code actually works against, and it's where the outcome of each
-- attempt is recorded: the resulting Meta post ID, the public permalink,
-- or the error if it failed.
-- ---------------------------------------------------------------------
create table post_targets (
  id                uuid primary key default gen_random_uuid(),
  post_id           uuid not null references posts (id) on delete cascade,
  social_account_id uuid not null references social_accounts (id) on delete cascade,
  status            target_status not null default 'pending',
  -- Meta's ID for the published item, once it exists. Storing this is
  -- what lets us fetch metrics for it later, and stops us double-posting
  -- if a retry happens after a success we didn't record in time.
  platform_post_id  text,
  permalink         text,
  published_at      timestamptz,
  error_message     text,
  attempt_count     integer not null default 0,
  last_attempt_at   timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  constraint post_targets_unique_account unique (post_id, social_account_id)
);

create index post_targets_post_id_idx on post_targets (post_id);
create index post_targets_account_idx on post_targets (social_account_id);
-- Lets the publisher find work to do, and phase 5 retry failed targets.
create index post_targets_status_idx on post_targets (status)
  where status in ('pending', 'publishing', 'failed');


-- ---------------------------------------------------------------------
-- approval_requests — the private link you send to a client
--
-- SECURITY: we store only a hash of the link token, never the token
-- itself — the same way passwords are handled. The raw token is shown to
-- you once, when the link is generated, and then it only exists in the
-- URL you sent the client. If this database were ever exposed, the
-- hashes in it could not be turned back into working approval links.
--
-- expires_at is mandatory: an approval link that works forever is a
-- liability once it's been forwarded around a client's inbox.
-- ---------------------------------------------------------------------
create table approval_requests (
  id                 uuid primary key default gen_random_uuid(),
  organization_id    uuid not null references organizations (id) on delete cascade,
  post_id            uuid not null references posts (id) on delete cascade,
  token_hash         text not null unique,
  expires_at         timestamptz not null,
  revoked_at         timestamptz,
  created_by_user_id uuid references users (id) on delete set null,
  created_at         timestamptz not null default now()
);

create index approval_requests_post_id_idx on approval_requests (post_id);
create index approval_requests_expiry_idx on approval_requests (expires_at)
  where revoked_at is null;


-- ---------------------------------------------------------------------
-- approvals — the record of what a client actually decided
--
-- Kept separate from approval_requests so the full back-and-forth
-- survives: a post can be sent for approval, get changes requested,
-- be revised, and be approved on the second round. Both decisions stay
-- on the record.
--
-- ip_address and user_agent are captured because with passwordless links
-- they are the only evidence of who acted. If a client later says "I
-- never approved that", this is the answer.
-- ---------------------------------------------------------------------
create table approvals (
  id                  uuid primary key default gen_random_uuid(),
  post_id             uuid not null references posts (id) on delete cascade,
  approval_request_id uuid references approval_requests (id) on delete set null,
  decision            approval_decision not null,
  comment             text,
  -- Typed by the client on the approval page, e.g. "Sam Chen".
  decided_by_name     text,
  decided_at          timestamptz not null default now(),
  ip_address          inet,
  user_agent          text
);

create index approvals_post_id_idx on approvals (post_id, decided_at desc);


-- ---------------------------------------------------------------------
-- post_metrics — performance of a published post over time
--
-- Each row is a snapshot taken at a moment. Keeping a history rather
-- than one running total means the analytics dashboard can show how a
-- post accumulated engagement, not just where it ended up.
--
-- `raw` keeps Meta's untouched JSON response. Whenever Meta adds a
-- metric we didn't anticipate, the data is already captured and we can
-- backfill a proper column later instead of having lost it.
-- ---------------------------------------------------------------------
create table post_metrics (
  id              uuid primary key default gen_random_uuid(),
  post_target_id  uuid not null references post_targets (id) on delete cascade,
  collected_at    timestamptz not null default now(),
  impressions     integer,
  reach           integer,
  likes           integer,
  comments        integer,
  saves           integer,
  shares          integer,
  video_views     integer,
  engagement_rate numeric(7, 4),
  raw             jsonb,

  constraint post_metrics_unique_snapshot unique (post_target_id, collected_at)
);

create index post_metrics_target_idx on post_metrics (post_target_id, collected_at desc);


-- ---------------------------------------------------------------------
-- account_metrics — follower counts and reach, one row per day
--
-- Daily granularity, so re-running a collection for the same day
-- overwrites rather than duplicates (see the unique constraint).
-- ---------------------------------------------------------------------
create table account_metrics (
  id                uuid primary key default gen_random_uuid(),
  social_account_id uuid not null references social_accounts (id) on delete cascade,
  metric_date       date not null,
  followers         integer,
  follows           integer,
  media_count       integer,
  impressions       integer,
  reach             integer,
  profile_views     integer,
  raw               jsonb,
  created_at        timestamptz not null default now(),

  constraint account_metrics_unique_day unique (social_account_id, metric_date)
);

create index account_metrics_account_idx on account_metrics (social_account_id, metric_date desc);


-- ---------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------
create trigger organizations_set_updated_at
  before update on organizations
  for each row execute function set_updated_at();

create trigger users_set_updated_at
  before update on users
  for each row execute function set_updated_at();

create trigger clients_set_updated_at
  before update on clients
  for each row execute function set_updated_at();

create trigger social_accounts_set_updated_at
  before update on social_accounts
  for each row execute function set_updated_at();

create trigger posts_set_updated_at
  before update on posts
  for each row execute function set_updated_at();

create trigger post_targets_set_updated_at
  before update on post_targets
  for each row execute function set_updated_at();


-- ---------------------------------------------------------------------
-- Lock the front door (important — please read)
--
-- Supabase automatically publishes every table in the `public` schema as
-- a REST API, reachable with the "anon" key. That key is not a secret:
-- it ships inside the frontend and anyone can read it out of the browser.
--
-- Turning on Row Level Security while defining NO policies means those
-- public roles can read and write exactly nothing. The service role key
-- our Express backend uses bypasses RLS entirely, so the backend keeps
-- full access and remains the only way into this data.
--
-- Net effect: the database is closed to the internet, and all access
-- rules live in our API where we can reason about them. If we later
-- want the frontend to query Supabase directly, we add policies then.
-- ---------------------------------------------------------------------
alter table organizations    enable row level security;
alter table users            enable row level security;
alter table clients          enable row level security;
alter table social_accounts  enable row level security;
alter table posts            enable row level security;
alter table post_media       enable row level security;
alter table post_targets     enable row level security;
alter table approval_requests enable row level security;
alter table approvals        enable row level security;
alter table post_metrics     enable row level security;
alter table account_metrics  enable row level security;
